### ISSUE TITLE
Uncaught TypeError: Cannot read property 'field' of undefined

### ISSUE THREAD

**Issue by dharmatech** [wenzhixin/bootstrap-table#5765]
Codepen with table which uses bootstrap table:

https://codepen.io/dharmatech/pen/xxqQwqV?editors=1000

Chrome DevTools shows the following when loading that page:

```
jquery.min.js:2 jQuery.Deferred exception: Cannot read property 'field' of undefined TypeError: Cannot read property 'field' of undefined
    at HTMLTableCellElement.<anonymous> (https://unpkg.com/bootstrap-table@1.18.3/dist/bootstrap-table.min.js:10:48007)
    at Function.each (https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js:2:3003)
    at S.fn.init.each (https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js:2:1481)
    at HTMLTableRowElement.<anonymous> (https://unpkg.com/bootstrap-table@1.18.3/dist/bootstrap-table.min.js:10:47811)
    at Function.each (https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js:2:3003)
    at S.fn.init.each (https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js:2:1481)
    at Object.trToData (https://unpkg.com/bootstrap-table@1.18.3/dist/bootstrap-table.min.js:10:47644)
    at t.value (https://unpkg.com/bootstrap-table@1.18.3/dist/bootstrap-table.min.js:10:56401)
    at t.value (https://unpkg.com/bootstrap-table@1.18.3/dist/bootstrap-table.min.js:10:51858)
    at HTMLTableElement.<anonymous> (https://unpkg.com/bootstrap-table@1.18.3/dist/bootstrap-table.min.js:10:119786) undefined
S.Deferred.exceptionHook @ jquery.min.js:2
jquery.min.js:2 Uncaught TypeError: Cannot read property 'field' of undefined
    at HTMLTableCellElement.<anonymous> (bootstrap-table.min.js:10)
    at Function.each (jquery.min.js:2)
    at S.fn.init.each (jquery.min.js:2)
    at HTMLTableRowElement.<anonymous> (bootstrap-table.min.js:10)
    at Function.each (jquery.min.js:2)
    at S.fn.init.each (jquery.min.js:2)
    at Object.trToData (bootstrap-table.min.js:10)
    at t.value (bootstrap-table.min.js:10)
    at t.value (bootstrap-table.min.js:10)
    at HTMLTableElement.<anonymous> (bootstrap-table.min.js:10)
```

Thank you for any suggestions!

**Comment by wenzhixin** [comment]
Working example: https://live.bootstrap-table.com/code/wenzhixin/8005

**Comment by dharmatech** [comment]
@wenzhixin,

Thank you for the working example.

Based on the changes you made, it seems like the issue is the blank `th` elements?

Is this documented somewhere? I.e. that empty `th` elements are not allowed?

Thank you.
