### ISSUE TITLE
Editable with Bootstrap 5?

### ISSUE THREAD

**Issue by saleh-esmaili** [wenzhixin/bootstrap-table#6034]
### Description

Hi, So I use `bootstrap 5` in my project, I want to enable editable in my table columns, But looks like `x-editable` dose not support `bootstrap 5` and didnt update for so long. Example of editable is working fine in `bootstrap 3` that uses `bootstrap-table-editable`, but in `bootstrap 4` example code have some issues... Is n't there any plugin for `bootstrap 5` editable?

**Comment by josh-gaby** [comment]
For anyone else coming across this needing to use editable with bootstrap 5, I've managed to get it working by including the files from the bootstrap 5 build of [this  fork of x-editable](https://github.com/skycyclone/x-editable/tree/develop/dist/bootstrap5-editable)

Standard bootstrap-table files included:
```
<link rel="stylesheet" href="common/bootstrap-table-1.20.2/bootstrap-table.css" media="all">
<script type="text/javascript" src="common/bootstrap-table-1.20.2/bootstrap-table.js"></script>
<script type="text/javascript" src="common/bootstrap-table-1.20.2/extensions/editable/bootstrap-table-editable.js"></script>
```

Files included from x-editable fork:
```
<link rel="stylesheet" href="common/x-editable/x-editable.css" media="all">
<script type="text/javascript" src="common/x-editable/x-editable.js"></script>
```

**Comment by mfs-edu** [comment]
@josh-gaby - Are you using any other extensions? I can get the row in a data-editable="true" column to highlight (i.e., they turn into links). And when I click on one I can see the class editable-open get added to the a href. But there's no tool tip-y type "modal" to edit that field. 

Frankly, I'm blocked and am looking for anything change in perspective. 

p.s. I'm sandboxing in CodePen, any chance that might be an issue?

**Comment by Latisha19** [comment]
@josh-gaby Sadly I still failed...just need one step, I thought.

When I edit fin and click ok, I got:

```
tooltip.js:536 Uncaught TypeError: Cannot convert undefined or null to object
    at Object.values (<anonymous>)
    at un._isWithActiveTrigger (tooltip.js:536:19)
    at tooltip.js:268:16
    at m (index.js:254:5)
    at HTMLDivElement.a (index.js:276:5)
    at s (index.js:98:11)
    at index.js:282:7
```
(Error from Bootstrap (v5.2.3) tooltip.js)

All I use js is .min.js.
