### ISSUE TITLE
filter-control does not work when using rowspan or colspan or two <TR> tags.

### ISSUE THREAD

**Issue by du8die** [wenzhixin/bootstrap-table#6096]
### Bootstraptable version(s) affected

1.19.1

### Description

When placed inside a <thead> element with at least one column that spans a row or multiple columns, the filter-control is not displaying at all. I tested many different configurations, and none would work. As long as I had two rows in the header, or a Colspan or rowspan attribute somewhere in the header, the extension failed.

### Example(s)

https://live.bootstrap-table.com/code/du8die/11013

### Additional Context

This error popped up in the console...

`jQuery.Deferred exception: Cannot read properties of undefined (reading 'field') TypeError: Cannot read properties of undefined (reading 'field')
    at HTMLTableCellElement.<anonymous> (https://unpkg.com/bootstrap-table@1.19.1/dist/bootstrap-table.min.js:10:48689)
    at Function.each (https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js:2:2976)
    at S.fn.init.each (https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js:2:1454)
    at HTMLTableRowElement.<anonymous> (https://unpkg.com/bootstrap-table@1.19.1/dist/bootstrap-table.min.js:10:48493)
    at Function.each (https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js:2:2976)
    at S.fn.init.each (https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js:2:1454)
    at Object.trToData (https://unpkg.com/bootstrap-table@1.19.1/dist/bootstrap-table.min.js:10:48326)
    at p.value (https://unpkg.com/bootstrap-table@1.19.1/dist/bootstrap-table.min.js:10:57220)
    at p.value (https://unpkg.com/bootstrap-table@1.19.1/dist/bootstrap-table.min.js:10:52621)
    at p.value (https://unpkg.com/bootstrap-table@1.19.1/dist/extensions/filter-control/bootstrap-table-filter-control.min.js:10:35453) undefined`

**Comment by djhvscf** [comment]
The one that is failing is the core plugin. I'm not sure if the structure is invalid or it's valid but the plugin doesn't support it. @wenzhixin @UtechtDustin can you guys take a look?

![image](https://user-images.githubusercontent.com/4496763/162137786-bb67659d-fdde-4cee-9686-bc5971abd944.png)

**Comment by UtechtDustin** [comment]
The first header row don't have enough rows. There are 3 data columns `id`, `name` and `price`, but in the first row you only have one column (the column with rowspan - `id`).
That means you don't have a valid html table, you also can validate it with [validator w3.org](https://validator.w3.org/#validate_by_input) , you will get the warning `A table row was 3 columns wide and exceeded the column count established by the first row (1).`.
Add two more columns for `name` and `price` and the problem is fixed.
Example: https://live.bootstrap-table.com/code/UtechtDustin/11027

Is your example a minimal example ?
If not, i don't understand why you need the rowspan at all.
