### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'methods')

### ISSUE THREAD

**Issue by techmahedy** [wenzhixin/bootstrap-table#6183]
### Bootstraptable version(s) affected

1.20.2

### Description

This error is showing from my vue component. My Laravel version is 8 and Vue version is 2. How can I solve this error? Please check the error from below:

app.js:11050 Uncaught TypeError: Cannot read properties of undefined (reading 'methods')
    at app.js:11050:1658
    at app.js:11050:1739
    at app.js:11050:37
    at Object../node_modules/bootstrap-table/dist/bootstrap-table-vue.min.js (app.js:11050:43)
    at __webpack_require__ (app.js:66210:42)
    at Module../node_modules/babel-loader/lib/index.js??clonedRuleSet-5[0].rules[0].use[0]!./node_modules/vue-loader/lib/index.js??vue-loader-options!./resources/assets/js/components/MerchandizerComponent.vue?vue&type=script&lang=js& (app.js:10872:105)
    at __webpack_require__ (app.js:66210:42)
    at Module../resources/assets/js/components/MerchandizerComponent.vue?vue&type=script&lang=js& (app.js:53960:236)
    at __webpack_require__ (app.js:66210:42)
    at Module../resources/assets/js/components/MerchandizerComponent.vue (app.js:53922:109)

**Comment by djhvscf** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com/) to show your problem, thanks!

**Comment by UtechtDustin** [comment]
I will close this issue, because we got no response from you.
If you still need help, please provide us an example as @djhvscf asked for.
