### ISSUE TITLE
fixed-columns, filter-control with height causes "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by rsperumal** [wenzhixin/bootstrap-table#6386]
### Bootstraptable version(s) affected

1.21.0

### Description

I'm trying to get a table with fixed columns and filter on each column with static header row (using the height parameter).
I notice that the code produces "Uncaught RangeError: Maximum call stack size exceeded" when I try to search on the static columns. The non static columns work ok.
I have given the code below that I used in the online editor to reproduce the error
If I don't specify "height:600" for bootstrapTable, it works fine.
If I make the columns non-fixed, it works fine.
Please inspect the page to see the error (which I have pasted below)

unfortunately I'm not skilled enough to investigate this issue but I hope I have given you enough clues to find the root cause. Is there any way out to avoid this error?

Btw, this is such a wonderful plugin with lot of fancy features. Please keep up the good work.

### Example(s)

<link href="https://unpkg.com/bootstrap-table@1.21.0/dist/bootstrap-table.min.css" rel="stylesheet">

<script src="https://unpkg.com/bootstrap-table@1.21.0/dist/bootstrap-table.min.js"></script>
<script src="https://unpkg.com/bootstrap-table@1.21.0/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
<link href="https://unpkg.com/bootstrap-table@1.21.0/dist/extensions/fixed-columns/bootstrap-table-fixed-columns.min.css" rel="stylesheet">
<script src="https://unpkg.com/bootstrap-table@1.21.0/dist/extensions/fixed-columns/bootstrap-table-fixed-columns.min.js"></script>
<table
  id="table"
  data-url="json/data5.json"
  data-filter-control="true"
  data-show-search-clear-button="true">
  <thead>
    <tr>
      <th data-field="id">ID</th>
      <th data-field="name" data-filter-control="input">Item Name</th>
      <th data-field="price" data-filter-control="input">Item Price</th>
      <th data-field="column1" data-filter-control="input">column1</th>
      <th data-field="column2" data-filter-control="input">column2</th>
      <th data-field="column3" data-filter-control="input">column3</th>
      <th data-field="column4" data-filter-control="input">column4</th>
      <th data-field="column1" data-filter-control="input">column1</th>
      <th data-field="column2" data-filter-control="input">column2</th>
      <th data-field="column3" data-filter-control="input">column3</th>
      <th data-field="column4" data-filter-control="input">column4</th>
    </tr>
  </thead>
</table>

<script>
  $(function() {
    $('#table').bootstrapTable({fixedColumns: true,
            fixedNumber: 4, height: 600})
  })
</script>

### Additional Context

Error seen while inspecting the page:

Uncaught RangeError: Maximum call stack size exceeded
    at RegExp.exec (<anonymous>)
    at [Symbol.replace] (<anonymous>)
    at String.replace (<anonymous>)
    at se (jquery.min.js:2:7093)
    at se.matchesSelector (jquery.min.js:2:13178)
    at S.filter (jquery.min.js:2:24704)
    at D (jquery.min.js:2:24590)
    at S.fn.init.is (jquery.min.js:2:25199)
    at HTMLInputElement.<anonymous> (bootstrap-table-filter-control.min.js:10:46946)
    at HTMLTableSectionElement.dispatch (jquery.min.js:2:43090)

**Comment by delvingmeddler** [comment]
The example shows the problem clearly. Also I noticed that if you make the browser page narrow enough, such that the fixed columns will be hiding some cells, then the rangeError occurs immediately on loading the example, without entering any filter data.

**Comment by shigure-j** [comment]
Encountered the same problem in 1.21.2 version.
The `triggerSearch` event will be invoked by the `change` or `keyup` event of fixed columns,
but inside `triggerSearch`, it invokes the `change` or `keyup` event of filter, it seems cause the endless loop.
https://github.com/wenzhixin/bootstrap-table/blob/fb79bc590dc8042c9d1d3359453e5184e082e7ff/src/extensions/fixed-columns/bootstrap-table-fixed-columns.js#L353-L369
https://github.com/wenzhixin/bootstrap-table/blob/fb79bc590dc8042c9d1d3359453e5184e082e7ff/src/extensions/filter-control/bootstrap-table-filter-control.js#L543-L555
I removed the `triggerSearch` invocation below, the loop disappeared, and the filter-control seems steel works, is this invocation redundant?
https://github.com/wenzhixin/bootstrap-table/blob/fb79bc590dc8042c9d1d3359453e5184e082e7ff/src/extensions/fixed-columns/bootstrap-table-fixed-columns.js#L368
