### ISSUE TITLE
Uncaught TypeError: Cannot set properties of undefined (setting 'BootstrapTable')

### ISSUE THREAD

**Issue by Nephiaust** [wenzhixin/bootstrap-table#6962]
### Bootstraptable version(s) affected

1.22.1

### Description

Trying to add in Bootstrap-table, but when I look at the console on the web browser it shows the following errors.

On Chrome
```
Uncaught TypeError: Cannot set properties of undefined (setting 'BootstrapTable')
    at bootstrap-table.js:8541:22
    at bootstrap-table.js:4:102
    at bootstrap-table.js:5:3
(anonymous) @ bootstrap-table.js:8541
(anonymous) @ bootstrap-table.js:4
(anonymous) @ bootstrap-table.js:5
```

On Firefox
```
Uncaught TypeError: $$p is undefined
    <anonymous> http://www.dev.nephi.id.au/test/js/bootstrap-table.js:8541
    <anonymous> http://www.dev.nephi.id.au/test/js/bootstrap-table.js:4
    <anonymous> http://www.dev.nephi.id.au/test/js/bootstrap-table.js:5
```

On Safari (cant get the lines, but 5, 4:110, 8541)
```
TypeError: undefined is not an object (evaluating '$$p.BootstrapTable = BootstrapTable')
```

### Example(s)

http://www.dev.nephi.id.au/test/search.php?query=iphone

### Additional Context

MacOS - 13.5.1 (22G90)
Chrome - Version 116.0.5845.140 (Official Build) (arm64)
Firefox - 117.0 (64-bit)
Safari - Version 16.6 (18615.3.12.11.2)

Server is a Debian 12, with PHP 8.2 on Apache/2.4.57

**Comment by Nephiaust** [comment]
Let me know if you need any more details or something?

Also the code for the site is here as well, if you need to look at what I have done :)
https://github.com/Nephiaust/Simple-PHP-Blog

**Comment by Nephiaust** [comment]
Turns out you need to have jquery loaded first.
