### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'fn')

### ISSUE THREAD

**Issue by Nephiaust** [wenzhixin/bootstrap-table#6963]
### Bootstraptable version(s) affected

1.22.1

### Description

I added the locale JS during troubleshooting #6962 and I get the following error

```
Uncaught TypeError: Cannot read properties of undefined (reading 'fn')
    at bootstrap-table-locale-all.js:1329:6
    at bootstrap-table-locale-all.js:4:77
    at bootstrap-table-locale-all.js:5:3
(anonymous) @ bootstrap-table-locale-all.js:1329
(anonymous) @ bootstrap-table-locale-all.js:4
(anonymous) @ bootstrap-table-locale-all.js:5
```

### Example(s)

http://www.dev.nephi.id.au/test/search.php?query=iphone

### Additional Context

Same info as #6962

**Comment by Nephiaust** [comment]
Let me know if you need any more details or something?

Also the code for the site is here as well, if you need to look at what I have done :)
https://github.com/Nephiaust/Simple-PHP-Blog

**Comment by Nephiaust** [comment]
Turns out you need to have jquery loaded first.
