### ISSUE TITLE
属性classes和height同时存在会发生严重错误

### ISSUE THREAD

**Issue by lyz0hzw** [wenzhixin/bootstrap-table#7116]
### Bootstraptable version(s) affected

1.22.1

### Description

当我使用配置项进行创建时，发现当classes属性和height属性同时存在，页面会报错误，错误原因是由于对一个数组进行了split操作：

> bootstrap-table.min.js:10 Uncaught TypeError: this.options.classes.split is not a function
    at n.value (bootstrap-table.min.js:10:69159)
    at n.value (bootstrap-table.min.js:10:66031)
    at HTMLTableElement.<anonymous> (bootstrap-table.min.js:10:136536)
    at Function.each (jquery.min.js:2:2976)
    at S.fn.init.each (jquery.min.js:2:1454)
    at t.fn.bootstrapTable (bootstrap-table.min.js:10:136080)
    at basic-columns.html:2:39

### Example(s)

这是一个我复现的代码：https://live.bootstrap-table.com/code/lyz0hzw/16886

**Comment by wenzhixin** [comment]
用法不对，`classes` 应该是字符串，空格分开，如： `classes: 'a b'`
![image](https://github.com/wenzhixin/bootstrap-table/assets/2117018/fb84e6ef-1fc0-42d6-ba3c-748c2518996d)

https://live.bootstrap-table.com/code/wenzhixin/16923
