### ISSUE TITLE
Error when generating docs.

### ISSUE THREAD

**Issue by shuLhan** [wenzhixin/bootstrap-table#741]
Bootstrap-table revision 43c691411908d3e750f7e7dc396c713f1c58332c.

Error message,
~~~~
~/git/bootstrap-table/docs
ms 1 % jekyll build -V -t
Configuration file: none
            Source: /home/ms/git/bootstrap-table/docs
       Destination: /home/ms/git/bootstrap-table/docs/_site
      Generating... 
/home/ms/git/bootstrap-table/docs/_plugins/multiple-languages.rb:23:in `process': undefined method `first' for nil:NilClass (NoMethodError)
        from /home/ms/.gem/ruby/2.2.0/gems/jekyll-2.5.3/lib/jekyll/command.rb:28:in `process_site'
        from /home/ms/.gem/ruby/2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:56:in `build'
        from /home/ms/.gem/ruby/2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:34:in `process'
        from /home/ms/.gem/ruby/2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        from /home/ms/.gem/ruby/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
        from /home/ms/.gem/ruby/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
        from /home/ms/.gem/ruby/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
        from /home/ms/.gem/ruby/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
        from /home/ms/.gem/ruby/2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
        from /home/ms/.gem/ruby/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
        from /home/ms/.gem/ruby/2.2.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
        from /home/ms/.gem/ruby/2.2.0/bin/jekyll:23:in `load'
        from /home/ms/.gem/ruby/2.2.0/bin/jekyll:23:in `<main>'
~~~~

How do I proceed?

**Comment by shuLhan** [comment]
Fixed. I must run jekyll on root directory.
~~~~
~/git/bootstrap-table
ms 0 % jekyll build --config _config.yml 
~~~~

Should've mention how to build the docs in the docs for "non-obvious-user" ;)
