### ISSUE TITLE
Cannot set properties of undefined (setting 'BootstrapTable')

### ISSUE THREAD

**Issue by virtualdreams** [wenzhixin/bootstrap-table#7510]
### Description

This is the only error I get.

```
bootstrap-table.min.js:10 
 Uncaught TypeError: Cannot set properties of undefined (setting 'BootstrapTable')
    at bootstrap-table.min.js:10:136671
    at bootstrap-table.min.js:10:233
    at bootstrap-table.min.js:10:245
(anonym)	@	bootstrap-table.min.js:10
(anonym)	@	bootstrap-table.min.js:10
(anonym)	@	bootstrap-table.min.js:10
```

I use Bootstrap 5 and this package and nothing works. What is missing?

```html
<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
 		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="stylesheet" href="/static/bootstrap.min.css">
		<link rel="stylesheet" href="/static/bootstrap-table.min.css">
		<title>Test</title>
	</head>
	<body>
		<div class="container">
			<table class="table table-sm table-striped" id="table" data-toggle="table" data-sort-class="table-active" data-sortable="true">
				<thead>
					<tr>
						<th data-field="id" data-sortable="true" scope="col">Name</th>
						<th data-field="combat" data-sortable="true" scope="col">Compatibility Level</th>
						<th data-field="owner" data-sortable="true" scope="col">Owner</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>Name 1</td>
						<td>Combar 1</td>
						<td>Owner 1</td>
					</tr>
					<tr>
						<td>Name 2</td>
						<td>Combar 2</td>
						<td>Owner 2</td>
					</tr>
				</tbody>
			</table>
        </div>
		
		<script language="javascript" type="text/javascript" src="/static/bootstrap.bundle.min.js"></script>
		<script language="javascript" type="text/javascript" src="/static/bootstrap-table.min.js"></script>
	</body>
</html>
```

**Comment by wenzhixin** [comment]
You need to include the jQuery library.

**Comment by wenzhixin** [comment]
ref https://github.com/wenzhixin/bootstrap-table/issues/4796

**Comment by virtualdreams** [comment]
Ok, thanks for the info. But then this information is missing in the documentation because I haven't found anything like it.

**Comment by wenzhixin** [comment]
https://bootstrap-table.com/docs/getting-started/introduction/#starter-template

Thanks for your feedback. We will consider adding it later.
